bigdatagenomics/utils

bdg-utils-misc/src/test/scala/org/bdgenomics/utils/misc/SparkFunSuite.scala

Resolves #20. Ports https://github.com/bigdatagenomics/adam/pull/557 over from ADAM.

[bdg-utils-20] Port unit testing suite fixes over from ADAM.

---

bdg-utils-parquet/src/main/scala/org/bdgenomics/utils/parquet/ParquetLister.scala
bdg-utils-parquet/src/main/scala/org/bdgenomics/utils/parquet/ParquetPartition.scala
pom.xml

Backporting https://github.com/bigdatagenomics/adam/commit/28778ffd42e35f2dea61a73a370a26b029e53962.

Porting a fix to Parquet from ADAM.

---

bdg-utils-statistics/src/main/scala/org/bdgenomics/utils/statistics/normalization/ZScoreNormalization.scala
bdg-utils-statistics/src/test/scala/org/bdgenomics/utils/statistics/normalization/ZScoreNormalizationSuite.scala

Depends on #13. See https://github.com/bigdatagenomics/adam/pull/629.

Move normalization code from ADAM

---

pom.xml
scripts/move_to_scala_2.11.sh
scripts/release/release.sh
scripts/release/rollback.sh
utils-cli/pom.xml
utils-io/pom.xml
utils-metrics/pom.xml
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ServoTimersAccumulableParam.scala
utils-minhash/pom.xml
utils-misc/pom.xml
utils-serialization/pom.xml
utils-statistics/pom.xml

Resolves #17. Reverts #34. Adds a stage that rewrites `pom.xml` files to run Scala 2.10.

Clean up for release

---

pom.xml

[utils-44] updating release tag name format to more closely match artifact name

---

pom.xml

Update spark, hadoop, and parquet dependency versions

---

pom.xml
utils-io/pom.xml
utils-metrics/pom.xml
utils-minhash/pom.xml
utils-misc/pom.xml
utils-serialization/pom.xml
utils-statistics/pom.xml

Makes the build go quite faster actually.

Remove extraneous git-commit-id-plugin configuration

---

pom.xml
utils-cli/pom.xml
utils-io/pom.xml
utils-metrics/pom.xml
utils-minhash/pom.xml
utils-misc/pom.xml
utils-serialization/pom.xml
utils-statistics/pom.xml

Must have missed pushing this commit when cutting the 0.2.4 release.
Fixes #66

Modifying pom.xml files to move back to Scala 2.10 for development.

---

.gitignore
pom.xml

[utils-70] Generate JAR with test sources as part of release process.

---

pom.xml
scripts/move_to_spark_2.sh
utils-cli/pom.xml
utils-intervalrdd/pom.xml
utils-io/pom.xml
utils-metrics/pom.xml
utils-metrics/src/main/scala/org/apache/spark/rdd/InstrumentedOrderedRDDFunctions.scala
utils-metrics/src/main/scala/org/apache/spark/rdd/InstrumentedPairRDDFunctions.scala
utils-metrics/src/main/scala/org/apache/spark/rdd/InstrumentedRDD.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MetricsListener.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ServoTimersAccumulableParam.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/SparkMetrics.scala
utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/MetricsListenerSuite.scala
utils-minhash/pom.xml
utils-misc/pom.xml
utils-serialization/pom.xml
utils-statistics/pom.xml

[UTILS-77] Support Spark 2.0.0.

---

utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MetricsRecorder.scala

Update the Metric Recorder to support asynchronous timing events.
Resolves #65

MetricRecorder thread async update

---

utils-misc/src/test/resources/test.txt
utils-misc/src/test/scala/org/bdgenomics/utils/misc/SparkFunSuite.scala
utils-misc/src/test/scala/org/bdgenomics/utils/misc/SparkFunSuiteSuite.scala

Resolves #88.
Hold on merging until tested downstream with ADAM.

[UTILS-88] Move ADAMFunSuite functions upstream.

---

utils-cli/src/main/scala/org/bdgenomics/utils/cli/BDGCommand.scala

[UTILS-83] Remove "adam" from Spark application name.

---

scripts/jenkins-test
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/HashStore.scala
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/MinHash.scala
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/MinHashBucketKey.scala
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/MinHashSignature.scala
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/MinHashable.scala
utils-minhash/src/main/scala/org/bdgenomics/utils/minhash/MinHashableRDD.scala
utils-minhash/src/test/scala/org/bdgenomics/utils/minhash/MinHashSignatureSuite.scala
utils-minhash/src/test/scala/org/bdgenomics/utils/minhash/MinHashSuite.scala

Resolves #82. Also useful, as it will allow us to clean up our temporary
testing cruft at the end of all test runs, but I don't think we actually
create much cruft in utils.

[UTILS-82] Add a Jenkins test script that runs tests in a unique tempdir

---

pom.xml

updated java and scoverage versions

---

utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/rdd/IntervalPartition.scala
utils-intervalrdd/src/test/scala/org/bdgenomics/utils/interval/rdd/IntervalPartitionSuite.scala

Issue https://github.com/bigdatagenomics/utils/issues/99

IntervalPartition now sorts elements before creating IntervalArray

---

scripts/jenkins-test
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ASCIITable.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/InstrumentationFunctions.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/Metrics.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MonitorTable.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/SparkMetrics.scala
utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/ASCIITableSuite.scala
utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/MonitorTableSuite.scala

[UTILS-105] Add toString function to Metrics.

---

utils-metrics/src/main/scala/org/apache/spark/rdd/InstrumentedRDD.scala

Resolves #109.
Still testing locally.

[UTILS-109] Wrap cache/persist methods from InstrumentedRDD.

---

utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala

[UTILS-114] Add abstract duplicate method to IntervalArray.

---

pom.xml
scripts/jenkins-test
utils-cli/pom.xml
utils-intervalrdd/pom.xml
utils-io/pom.xml
utils-metrics/pom.xml
utils-minhash/pom.xml
utils-misc/pom.xml
utils-misc/src/test/scala/org/bdgenomics/utils/misc/SparkFunSuite.scala
utils-serialization/pom.xml
utils-statistics/pom.xml

 [UTILS-120] Set up SparkSession in SparkFunSuite

---

pom.xml

[UTILS-118]  Update args4j dependency version to 2.33

---

pom.xml
utils-cli/pom.xml
utils-cli/src/main/scala/org/bdgenomics/utils/cli/BDGCommand.scala
utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/rdd/IntervalPartition.scala
utils-io/src/main/scala/org/bdgenomics/utils/io/HTTPRangedByteAccess.scala
utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/MetricsSuite.scala
utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/SparkMetricsSuite.scala
utils-misc/src/main/scala/org/bdgenomics/utils/misc/Logging.scala
utils-statistics/pom.xml
utils-statistics/src/main/scala/org/bdgenomics/utils/statistics/mixtures/DiscreteKMeansMixtureModel.scala
utils-statistics/src/main/scala/org/bdgenomics/utils/statistics/mixtures/DiscreteMixtureModel.scala
utils-statistics/src/main/scala/org/bdgenomics/utils/statistics/normalization/ZScoreNormalization.scala

[UTILS-131] Deprecate and remove usage of Logging trait.

---

scripts/release/release.sh

[UTILS-130] Adding github-changes-maven-plugin configuration to release script.

---

pom.xml

[UTILS-140] Update Spark dependency version to 2.4.3

---

utils-misc/src/main/scala/org/bdgenomics/utils/misc/HadoopUtil.scala
utils-misc/src/main/scala/org/bdgenomics/utils/misc/Logging.scala

[UTILS-142] Deprecate HadoopUtil, version 1.x is no longer supported

---

scripts/move_to_scala_2.11.sh
scripts/move_to_scala_2.12.sh

[UTILS-144] Update Scala 2.12 dependency version to 2.12.8

---

utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ASCIITable.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/DurationFormatting.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/InstrumentationFunctions.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/Metrics.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MetricsListener.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MetricsRecorder.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/MonitorTable.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/RecordedMetrics.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ServoTimer.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/ServoTimersAccumulableParam.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/SparkMetrics.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/package.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/metrics/Collection.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/metrics/Histogram.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/metrics/aggregators/Aggregator.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/metrics/aggregators/package.scala
utils-metrics/src/main/scala/org/bdgenomics/utils/metrics/package.scala

[UTILS-151] Deprecate utils-metrics for removal in version 0.3.0

---

pom.xml
scripts/move_to_spark_2.sh
scripts/move_to_spark_3.sh

[UTILS-164] Update Spark dependency version to 2.4.6

---

pom.xml

Update Spark dependency version to 3.2.1, guava to 31.1-jre
